version: "3.9"

services:
  backend:
    build: ./backend
    container_name: correios-backend
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - ./backend/.env
    expose:
      - "8000"
    networks:
      - correios-net

  frontend:
    build: ./frontend
    container_name: correios-frontend
    networks:
      - correios-net

  nginx:
    image: nginx:alpine
    container_name: correios-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - correios-net

volumes:
  static_volume:
  media_volume:

networks:
  correios-net:
    driver: bridge
