services:
  backend:
    build:
      context: ./backend
    container_name: correios-backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - correios-net

  frontend:
    build:
      context: ./frontend
    container_name: correios-frontend
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    networks:
      - correios-net

networks:
  correios-net:
    driver: bridge
