version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: correios-backend
    command: >
      sh -c "python manage.py migrate &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    expose:
      - "8000"
    networks:
      - correios-net

  frontend:
    build:
      context: ./frontend
    container_name: correios-frontend
    command: ["npm", "run", "build"]
    volumes:
      - ./frontend:/app
    networks:
      - correios-net

  nginx:
  image: nginx:latest
  container_name: correios-nginx
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./frontend/dist:/usr/share/nginx/html:ro
    - ./nginx/certs/star_faama_edu_br.crt:/etc/ssl/certs/star_faama_edu_br.crt:ro
    - ./nginx/certs/faama.edu.br.key:/etc/ssl/certs/faama.edu.br.key:ro
  ports:
    - "80:80"
    - "443:443"
  depends_on:
    - backend
    - frontend
  networks:
    - correios-net


networks:
  correios-net:
    driver: bridge
