# Generated by Django 5.2.6 on 2025-09-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('tipo_acesso', models.CharField(choices=[('SECRETARIA', 'Secretaria'), ('FUNCIONARIO', 'Funcionário'), ('ADMINISTRADOR', 'Administrador')], max_length=20)),
            ],
        ),
    ]
