# Generated by Django 5.2.6 on 2025-09-09 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_destinatario', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('RECEBIDO', 'Recebido'), ('ENTREGUE', 'Entregue'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=20)),
                ('data_chegada', models.DateTimeField(auto_now_add=True)),
                ('data_retirada', models.DateTimeField(blank=True, null=True)),
                ('foto_encomenda_recebida', models.ImageField(blank=True, null=True, upload_to='encomendas/recebidas/')),
                ('foto_encomenda_entregue', models.ImageField(blank=True, null=True, upload_to='encomendas/entregues/')),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encomendas_cadastradas', to=settings.AUTH_USER_MODEL)),
                ('entregue_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encomendas_entregues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
