# Generated by Django 5.2.6 on 2025-09-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='observacao',
            field=models.TextField(blank=True, help_text='Observações sobre a encomenda (ex: condições, detalhes da entrega)', null=True),
        ),
    ]
